pipeline{
   agent any
       stages {
           stage('one') {
                 steps {
                       echo "hi hello"
                       }
                        }
       stage ('two')
         {
            steps {
               input('do you want to continue?')
                  }
          }
      stage('Three')
        when {
            not  {
                branch "master"
                 }
             }
        steps {
         echo "hello"
              }
            }
      }
 }